// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: qbscnkjnhkuphysdldct

class SupabaseConfig {
  static const String supabaseUrl = 'https://qbscnkjnhkuphysdldct.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFic2Nua2puaGt1cGh5c2RsZGN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM0Njc0ODIsImV4cCI6MjA4OTA0MzQ4Mn0.XmDBXPnNOL3WKscvq4-ZIeiE2Vq14L0SvZuHJuV0ubg';
}
